#easy_admin_bundle:
#    resource: "@EasyAdminBundle/Controller/"
#    type:     annotation
#    prefix:   /admin
    
    


    
app_corredores_rioja:
    resource: "@AppCorredoresRiojaBundle/Resources/config/routing.yml"
    type: be_simple_i18n    

  
    
home:
    path: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: portada}


admin_home:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix:   /admin
    
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin